# Generated by Django 3.2.3 on 2021-05-30 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.CreateModel(
            name='AddAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, default='ADDRESS_LINE_1', max_length=100)),
                ('address_line_2', models.CharField(blank=True, default='ADDRESS_LINE_2', max_length=100)),
                ('phone', models.CharField(blank=True, default='98...', max_length=15)),
                ('city', models.CharField(blank=True, default='CITY', max_length=20)),
                ('state', models.CharField(blank=True, default='STATE', max_length=20)),
                ('country', models.CharField(blank=True, default='COUNTRY', max_length=20)),
                ('address_id', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
