# Generated by Django 3.2 on 2021-06-06 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_addemailaddress_addstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addaddress',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.addstate'),
        ),
    ]
