# Generated by Django 3.2 on 2021-06-06 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_addstate_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address_line_1', models.CharField(blank=True, default='ADDRESS_LINE_1', max_length=100)),
                ('address_line_2', models.CharField(blank=True, default='ADDRESS_LINE_2', max_length=100)),
                ('phone', models.CharField(blank=True, default='98...', max_length=15)),
                ('city', models.CharField(blank=True, default='CITY', max_length=20)),
                ('country', models.CharField(blank=True, default='COUNTRY', max_length=20)),
                ('feedback', models.TextField(max_length=800)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.addstate')),
            ],
        ),
    ]
