# Generated by Django 3.2.3 on 2021-06-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='city',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='country',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='state',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='city',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='country',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='state',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(blank=True, default='98...', max_length=10),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(blank=True, default='98...', max_length=10),
        ),
    ]
