# Generated by Django 3.2.3 on 2021-05-17 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_bloodcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='blood_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.bloodcategory'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
    ]
