# Generated by Django 3.2 on 2021-05-24 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_appointments_blood_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desctiption',
            new_name='pincode_delivery_check',
        ),
        migrations.AddField(
            model_name='product',
            name='detailed_description_panel',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_details',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ProductDetailedDescriptionPanelCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_description', models.TextField(blank=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
