# Generated by Django 3.2.3 on 2021-05-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='appointment_recieved_by_client',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='checked_and_ready_for_shipping',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='delivery_guy_checked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='appointments',
            name='time_slot',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
