# Generated by Django 3.2 on 2021-06-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_appointments_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
