# Generated by Django 3.2.3 on 2021-06-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_appointments_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='is_appointed',
            new_name='bloodAnalysed',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='is_billed',
            new_name='bloodCollected',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='appointment_recieved_by_client',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='checked_and_ready_for_shipping',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='delivery_guy_checked',
        ),
        migrations.AddField(
            model_name='appointments',
            name='reportUploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointments',
            name='vendorConfirmation',
            field=models.BooleanField(default=False),
        ),
    ]
