# Generated by Django 3.2.3 on 2021-06-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210614_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
    ]
