# Generated by Django 3.2 on 2021-07-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_appointments_is_billed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='blood_category',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
