# Generated by Django 3.2 on 2021-07-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_appointments_blood_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='blood_category_detail',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
