# Generated by Django 3.2 on 2021-07-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_appointments_blood_category_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
